/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

// Source: schema.json
export type SanityImageAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
};

export type About = {
  _id: string;
  _type: "about";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  heading?: string;
  bio?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  portrait?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  email?: string;
  linkedinUrl?: string;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type JournalPage = {
  _id: string;
  _type: "journalPage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  description?: string;
};

export type JournalPostReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "journalPost";
};

export type SanityFileAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.fileAsset";
};

export type Project = {
  _id: string;
  _type: "project";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  shortDescription?: string;
  fullDescription?: string;
  techStack?: Array<string>;
  siteUrl?: string;
  caseStudy?: JournalPostReference;
  coverMedia?: {
    type?: "image" | "video";
    image?: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    };
    video?: {
      asset?: SanityFileAssetReference;
      media?: unknown;
      _type: "file";
    };
  };
  images?: Array<{
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
    _key: string;
  }>;
  videos?: Array<{
    asset?: SanityFileAssetReference;
    media?: unknown;
    _type: "file";
    _key: string;
  }>;
  order?: number;
};

export type ProjectReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "project";
};

export type JournalPost = {
  _id: string;
  _type: "journalPost";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  excerpt?: string;
  body?: Array<
    | {
        children?: Array<{
          marks?: Array<string>;
          text?: string;
          _type: "span";
          _key: string;
        }>;
        style?:
          | "normal"
          | "h1"
          | "h2"
          | "h3"
          | "h4"
          | "h5"
          | "h6"
          | "blockquote";
        listItem?: "bullet" | "number";
        markDefs?: Array<{
          href?: string;
          _type: "link";
          _key: string;
        }>;
        level?: number;
        _type: "block";
        _key: string;
      }
    | {
        asset?: SanityImageAssetReference;
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        _type: "image";
        _key: string;
      }
    | {
        text?: string;
        attribution?: string;
        _type: "quote";
        _key: string;
      }
  >;
  coverImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  tags?: Array<string>;
  publishedAt?: string;
  relatedProject?: ProjectReference;
};

export type Slug = {
  _type: "slug";
  current?: string;
  source?: string;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes =
  | SanityImageAssetReference
  | About
  | SanityImageCrop
  | SanityImageHotspot
  | JournalPage
  | JournalPostReference
  | SanityFileAssetReference
  | Project
  | ProjectReference
  | JournalPost
  | Slug
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint;

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: src/sanity/lib/queries.ts
// Variable: ABOUT_QUERY
// Query: *[_type == "about"][0] {    heading,    bio,    portrait,    email,    linkedinUrl  }
export type ABOUT_QUERY_RESULT = {
  heading: string | null;
  bio: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "blockquote" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "normal";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }> | null;
  portrait: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  } | null;
  email: string | null;
  linkedinUrl: string | null;
} | null;

// Source: src/sanity/lib/queries.ts
// Variable: PROJECTS_QUERY
// Query: *[_type == "project"] | order(order asc) {   _id,  title,  slug,  shortDescription,  fullDescription,  techStack,  siteUrl,  caseStudy->{ _id, slug },  coverMedia,  images,  videos,  order }
export type PROJECTS_QUERY_RESULT = Array<{
  _id: string;
  title: string | null;
  slug: Slug | null;
  shortDescription: string | null;
  fullDescription: string | null;
  techStack: Array<string> | null;
  siteUrl: string | null;
  caseStudy: {
    _id: string;
    slug: Slug | null;
  } | null;
  coverMedia: {
    type?: "image" | "video";
    image?: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    };
    video?: {
      asset?: SanityFileAssetReference;
      media?: unknown;
      _type: "file";
    };
  } | null;
  images: Array<{
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
    _key: string;
  }> | null;
  videos: Array<{
    asset?: SanityFileAssetReference;
    media?: unknown;
    _type: "file";
    _key: string;
  }> | null;
  order: number | null;
}>;

// Source: src/sanity/lib/queries.ts
// Variable: PROJECT_BY_SLUG_QUERY
// Query: *[_type == "project" && slug.current == $slug][0] {   _id,  title,  slug,  shortDescription,  fullDescription,  techStack,  siteUrl,  caseStudy->{ _id, slug },  coverMedia,  images,  videos,  order }
export type PROJECT_BY_SLUG_QUERY_RESULT = {
  _id: string;
  title: string | null;
  slug: Slug | null;
  shortDescription: string | null;
  fullDescription: string | null;
  techStack: Array<string> | null;
  siteUrl: string | null;
  caseStudy: {
    _id: string;
    slug: Slug | null;
  } | null;
  coverMedia: {
    type?: "image" | "video";
    image?: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    };
    video?: {
      asset?: SanityFileAssetReference;
      media?: unknown;
      _type: "file";
    };
  } | null;
  images: Array<{
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
    _key: string;
  }> | null;
  videos: Array<{
    asset?: SanityFileAssetReference;
    media?: unknown;
    _type: "file";
    _key: string;
  }> | null;
  order: number | null;
} | null;

// Source: src/sanity/lib/queries.ts
// Variable: JOURNAL_PAGE_QUERY
// Query: *[_type == "journalPage"][0] { description }
export type JOURNAL_PAGE_QUERY_RESULT = {
  description: string | null;
} | null;

// Source: src/sanity/lib/queries.ts
// Variable: JOURNAL_POSTS_QUERY
// Query: *[_type == "journalPost"] | order(publishedAt desc) {   _id,  title,  slug,  excerpt,  coverImage,  tags,  publishedAt,  relatedProject->{ _id, title, slug } }
export type JOURNAL_POSTS_QUERY_RESULT = Array<{
  _id: string;
  title: string | null;
  slug: Slug | null;
  excerpt: string | null;
  coverImage: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  } | null;
  tags: Array<string> | null;
  publishedAt: string | null;
  relatedProject: {
    _id: string;
    title: string | null;
    slug: Slug | null;
  } | null;
}>;

// Source: src/sanity/lib/queries.ts
// Variable: JOURNAL_POST_BY_SLUG_QUERY
// Query: *[_type == "journalPost" && slug.current == $slug][0] {   _id,  title,  slug,  excerpt,  coverImage,  tags,  publishedAt,  relatedProject->{ _id, title, slug }, body }
export type JOURNAL_POST_BY_SLUG_QUERY_RESULT = {
  _id: string;
  title: string | null;
  slug: Slug | null;
  excerpt: string | null;
  coverImage: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  } | null;
  tags: Array<string> | null;
  publishedAt: string | null;
  relatedProject: {
    _id: string;
    title: string | null;
    slug: Slug | null;
  } | null;
  body: Array<
    | {
        children?: Array<{
          marks?: Array<string>;
          text?: string;
          _type: "span";
          _key: string;
        }>;
        style?:
          | "blockquote"
          | "h1"
          | "h2"
          | "h3"
          | "h4"
          | "h5"
          | "h6"
          | "normal";
        listItem?: "bullet" | "number";
        markDefs?: Array<{
          href?: string;
          _type: "link";
          _key: string;
        }>;
        level?: number;
        _type: "block";
        _key: string;
      }
    | {
        asset?: SanityImageAssetReference;
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        _type: "image";
        _key: string;
      }
    | {
        text?: string;
        attribution?: string;
        _type: "quote";
        _key: string;
      }
  > | null;
} | null;

// Source: src/sanity/lib/queries.ts
// Variable: PROJECT_SLUGS_QUERY
// Query: *[_type == "project" && defined(slug.current)]{ "slug": slug.current }
export type PROJECT_SLUGS_QUERY_RESULT = Array<{
  slug: string | null;
}>;

// Source: src/sanity/lib/queries.ts
// Variable: JOURNAL_POST_SLUGS_QUERY
// Query: *[_type == "journalPost" && defined(slug.current)]{ "slug": slug.current }
export type JOURNAL_POST_SLUGS_QUERY_RESULT = Array<{
  slug: string | null;
}>;

// Source: src/sanity/lib/queries.ts
// Variable: RELATED_JOURNAL_POSTS_QUERY
// Query: *[_type == "journalPost" && _id != $id] | order(publishedAt desc) {   _id,  title,  slug,  excerpt,  coverImage,  tags,  publishedAt,  relatedProject->{ _id, title, slug } }
export type RELATED_JOURNAL_POSTS_QUERY_RESULT = Array<{
  _id: string;
  title: string | null;
  slug: Slug | null;
  excerpt: string | null;
  coverImage: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  } | null;
  tags: Array<string> | null;
  publishedAt: string | null;
  relatedProject: {
    _id: string;
    title: string | null;
    slug: Slug | null;
  } | null;
}>;

// Source: src/sanity/lib/queries.ts
// Variable: NEXT_PROJECT_QUERY
// Query: coalesce(    *[_type == "project" && order > $currentOrder] | order(order asc) [0] { title, slug },    *[_type == "project"] | order(order asc) [0] { title, slug }  )
export type NEXT_PROJECT_QUERY_RESULT = {
  title: string | null;
  slug: Slug | null;
} | null;

// Query TypeMap
import "@sanity/client";
declare module "@sanity/client" {
  interface SanityQueries {
    '\n  *[_type == "about"][0] {\n    heading,\n    bio,\n    portrait,\n    email,\n    linkedinUrl\n  }\n': ABOUT_QUERY_RESULT;
    '\n  *[_type == "project"] | order(order asc) { \n  _id,\n  title,\n  slug,\n  shortDescription,\n  fullDescription,\n  techStack,\n  siteUrl,\n  caseStudy->{ _id, slug },\n  coverMedia,\n  images,\n  videos,\n  order\n }\n': PROJECTS_QUERY_RESULT;
    '\n  *[_type == "project" && slug.current == $slug][0] { \n  _id,\n  title,\n  slug,\n  shortDescription,\n  fullDescription,\n  techStack,\n  siteUrl,\n  caseStudy->{ _id, slug },\n  coverMedia,\n  images,\n  videos,\n  order\n }\n': PROJECT_BY_SLUG_QUERY_RESULT;
    '\n  *[_type == "journalPage"][0] { description }\n': JOURNAL_PAGE_QUERY_RESULT;
    '\n  *[_type == "journalPost"] | order(publishedAt desc) { \n  _id,\n  title,\n  slug,\n  excerpt,\n  coverImage,\n  tags,\n  publishedAt,\n  relatedProject->{ _id, title, slug }\n }\n': JOURNAL_POSTS_QUERY_RESULT;
    '\n  *[_type == "journalPost" && slug.current == $slug][0] { \n  _id,\n  title,\n  slug,\n  excerpt,\n  coverImage,\n  tags,\n  publishedAt,\n  relatedProject->{ _id, title, slug }\n, body }\n': JOURNAL_POST_BY_SLUG_QUERY_RESULT;
    '*[_type == "project" && defined(slug.current)]{ "slug": slug.current }': PROJECT_SLUGS_QUERY_RESULT;
    '*[_type == "journalPost" && defined(slug.current)]{ "slug": slug.current }': JOURNAL_POST_SLUGS_QUERY_RESULT;
    '\n  *[_type == "journalPost" && _id != $id] | order(publishedAt desc) { \n  _id,\n  title,\n  slug,\n  excerpt,\n  coverImage,\n  tags,\n  publishedAt,\n  relatedProject->{ _id, title, slug }\n }\n': RELATED_JOURNAL_POSTS_QUERY_RESULT;
    '\n  coalesce(\n    *[_type == "project" && order > $currentOrder] | order(order asc) [0] { title, slug },\n    *[_type == "project"] | order(order asc) [0] { title, slug }\n  )\n': NEXT_PROJECT_QUERY_RESULT;
  }
}
